#输入的视频文件
input: E:\movie\test\Rick.and.Morty.The.Anime.S01E08.1080p.AS.WEB-DL.ENG.AAC2.0.H.264-ToonsHub.mkv
#中间过程会生成的音频文件
output: E:\movie\test\Rick.and.Morty.The.Anime.S01E08.1080p.AS.WEB-DL.ENG.AAC2.0.H.264-ToonsHub.mp3
#生成的原始字幕文件
srt_path: E:\movie\test\Rick.and.Morty.The.Anime.S01E08.1080p.AS.WEB-DL.ENG.AAC2.0.H.264-ToonsHub.srt
#生成的翻译后的字幕文件
srt_translate_path: Rick.and.Morty.The.Anime.S01E08.1080p.AS.WEB-DL.ENG.AAC2.0.H.264-ToonsHub_zh.srt
#翻译时开启多少线程
translate_threads: 10
#翻译源语言
from: en
#翻译目标语言
to: zh
#huggingface model地址，例如 D:\download\pytorch_model.bin
hf_model_path: ""
#devive: cuda, cpu
device: cpu
