#输入的视频文件
input: D:\test\Rick.and.Morty.The.Anime.S01E08.mkv
#中间过程会生成的音频文件
output: D:\test\Rick.and.Morty.The.Anime.S01E08.mp3
#生成的原始字幕文件
srt_path: D:\test\Rick.and.Morty.The.Anime.S01E08.srt
#生成的翻译后的字幕文件
srt_translate_path: D:\test\Rick.and.Morty.The.Anime.S01E08_zh.srt
#翻译时开启多少线程
translate_threads: 10
#翻译源语言
from: en
#翻译目标语言
to: zh
#huggingface model地址，例如 D:\download\pytorch_model.bin
hf_model_path: ""
#调用设备: cuda, cpu
device: cuda
# Hugging face Token
hf_token: ""
